<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="org.openhab.binding.tinkerforge.internal.model"
    nsPrefix="model">
  <eClassifiers xsi:type="ecore:EDataType" name="MIPConnection" instanceClassName="com.tinkerforge.IPConnection"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerDevice" instanceClassName="com.tinkerforge.Device"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MLogger" instanceClassName="org.slf4j.Logger"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MAtomicBoolean" instanceClassName="java.util.concurrent.atomic.AtomicBoolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerforgeDevice" instanceClassName="com.tinkerforge.Device"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickDC" instanceClassName="com.tinkerforge.BrickDC"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletDualRelay" instanceClassName="com.tinkerforge.BrickletDualRelay"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletIndustrialQuadRelay"
      instanceClassName="com.tinkerforge.BrickletIndustrialQuadRelay"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletIndustrialDigitalIn4"
      instanceClassName="com.tinkerforge.BrickletIndustrialDigitalIn4"/>
  <eClassifiers xsi:type="ecore:EDataType" name="SwitchState" instanceClassName="org.openhab.binding.tinkerforge.internal.types.OnOffValue"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigitalValue" instanceClassName="org.openhab.binding.tinkerforge.internal.types.HighLowValue"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TinkerBrickletIO16" instanceClassName="com.tinkerforge.BrickletIO16"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickServo" instanceClassName="com.tinkerforge.BrickServo"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerforgeValue" instanceClassName="org.openhab.binding.tinkerforge.internal.types.TinkerforgeValue"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MDecimalValue" instanceClassName="org.openhab.binding.tinkerforge.internal.types.DecimalValue"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletHumidity" instanceClassName="com.tinkerforge.BrickletHumidity"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletDistanceIR" instanceClassName="com.tinkerforge.BrickletDistanceIR"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletTemperature" instanceClassName="com.tinkerforge.BrickletTemperature"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletBarometer" instanceClassName="com.tinkerforge.BrickletBarometer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletAmbientLight" instanceClassName="com.tinkerforge.BrickletAmbientLight"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MTinkerBrickletLCD20x4" instanceClassName="com.tinkerforge.BrickletLCD20x4"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TinkerBrickletRemoteSwitch" instanceClassName="com.tinkerforge.BrickletRemoteSwitch"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TinkerBrickletMotionDetector" instanceClassName="com.tinkerforge.BrickletMotionDetector"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TinkerBrickletMultiTouch" instanceClassName="com.tinkerforge.BrickletMultiTouch"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TinkerBrickletTemperatureIR" instanceClassName="com.tinkerforge.BrickletTemperatureIR"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Enum" instanceClassName="java.lang.Enum"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ecosystem">
    <eOperations name="getBrickd" unique="false" eType="#//MBrickd">
      <eParameters name="host" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="port" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getDevice" unique="false" eType="#//MBaseDevice">
      <eParameters name="uid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="subId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDevices4GenericId" unique="false" upperBound="-1">
      <eGenericType eClassifier="#//MSubDevice">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="uid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="genericId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="disconnect" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logger" unique="false"
        eType="#//MLogger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mbrickds" upperBound="-1"
        eType="#//MBrickd" containment="true" resolveProxies="false" eOpposite="#//MBrickd/ecosystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickd">
    <eOperations name="connect" unique="false"/>
    <eOperations name="disconnect" unique="false"/>
    <eOperations name="init" unique="false"/>
    <eOperations name="getDevice" unique="false" eType="#//MBaseDevice">
      <eParameters name="uid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logger" unique="false"
        eType="#//MLogger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipConnection" unique="false"
        eType="#//MIPConnection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="localhost"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4223"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConnected" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoReconnect" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reconnected" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2500"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdevices" upperBound="-1"
        containment="true" resolveProxies="false" eOpposite="#//MDevice/brickd">
      <eGenericType eClassifier="#//MDevice">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecosystem" eType="#//Ecosystem"
        eOpposite="#//Ecosystem/mbrickds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubDeviceAdmin" abstract="true" interface="true">
    <eOperations name="addSubDevice" unique="false">
      <eParameters name="subId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="subDeviceType" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTFConfigConsumer" abstract="true" interface="true">
    <eTypeParameters name="TFC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfConfig" containment="true"
        resolveProxies="false">
      <eGenericType eTypeParameter="#//MTFConfigConsumer/TFC"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBaseDevice" abstract="true" interface="true">
    <eOperations name="init" unique="false"/>
    <eOperations name="enable" unique="false"/>
    <eOperations name="disable" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logger" unique="false"
        eType="#//MLogger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledA" unique="false"
        eType="#//MAtomicBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDevice" abstract="true" interface="true"
      eSuperTypes="#//MBaseDevice">
    <eTypeParameters name="TF">
      <eBounds eClassifier="#//MTinkerforgeDevice"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tinkerforgeDevice" unique="false">
      <eGenericType eTypeParameter="#//MDevice/TF"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipConnection" unique="false"
        eType="#//MIPConnection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectedUid" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceIdentifier" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brickd" eType="#//MBrickd"
        eOpposite="#//MBrickd/mdevices"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSubDeviceHolder" abstract="true" interface="true">
    <eTypeParameters name="S">
      <eBounds eClassifier="#//MSubDevice">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eOperations name="initSubDevices" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msubdevices" upperBound="-1"
        containment="true" resolveProxies="false" eOpposite="#//MSubDevice/mbrick">
      <eGenericType eTypeParameter="#//MSubDeviceHolder/S"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MActor" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MSwitchActor" abstract="true" interface="true">
    <eOperations name="turnSwitch" unique="false">
      <eParameters name="state" unique="false" eType="#//SwitchState"/>
    </eOperations>
    <eOperations name="fetchSwitchState" unique="false" eType="#//SwitchState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="switchState" unique="false"
        eType="#//SwitchState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOutSwitchActor" abstract="true" interface="true"
      eSuperTypes="#//MSwitchActor"/>
  <eClassifiers xsi:type="ecore:EClass" name="MInSwitchActor" abstract="true" interface="true"
      eSuperTypes="#//MSwitchActor"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericDevice" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericDeviceId" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IODevice" abstract="true" interface="true">
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickletIO16"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//GenericDevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSubDevice" abstract="true" interface="true"
      eSuperTypes="#//MBaseDevice">
    <eTypeParameters name="B">
      <eBounds eClassifier="#//MSubDeviceHolder">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mbrick" eOpposite="#//MSubDeviceHolder/msubdevices">
      <eGenericType eTypeParameter="#//MSubDevice/B"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackListener" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callbackPeriod" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="1000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterruptListener" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debouncePeriod" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="100"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSensor" abstract="true" interface="true">
    <eTypeParameters name="DeviceValue">
      <eBounds eClassifier="#//MTinkerforgeValue"/>
    </eTypeParameters>
    <eOperations name="fetchSensorValue" unique="false">
      <eGenericType eTypeParameter="#//MSensor/DeviceValue"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorValue" unique="false">
      <eGenericType eTypeParameter="#//MSensor/DeviceValue"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTextActor" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLCDSubDevice" abstract="true" interface="true">
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickletLCD20x4"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickServo">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="brick_servo"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickServo"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MServo"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServo">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="servo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="velocity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="30000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceleration" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="30000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pulseWidthMin" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pulseWidthMax" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="19500"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputVoltage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="5000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="servoCurrentPosition" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="servoDestinationPosition"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eGenericSuperTypes eClassifier="#//MInSwitchActor"/>
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickServo"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFServoConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DCDriveMode">
    <eLiterals name="Brake"/>
    <eLiterals name="Coast" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickDC">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="brick_dc"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="velocity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentVelocity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceleration" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwmFrequency" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="15000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driveMode" unique="false"
        eType="#//DCDriveMode" defaultValueLiteral="Break"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="switchOnVelocity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort" defaultValueLiteral="10000"/>
    <eGenericSuperTypes eClassifier="#//MInSwitchActor"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickDC"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFBrickDCConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDualRelayBricklet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_dual_relay"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletDualRelay"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MDualRelay"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIndustrialQuadRelayBricklet">
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletIndustrialQuadRelay"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MIndustrialQuadRelay"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIndustrialQuadRelay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="industrial_quad_relay"/>
    <eGenericSuperTypes eClassifier="#//MInSwitchActor"/>
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MIndustrialQuadRelayBricklet"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletIndustrialDigitalIn4">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_industrial_digital_4in"/>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MIndustrialDigitalIn"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletIndustrialDigitalIn4"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//InterruptListener"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFInterruptListenerConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIndustrialDigitalIn">
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickletIndustrialDigitalIn4"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//DigitalValue"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalActor">
    <eOperations name="turnDigital" unique="false">
      <eParameters name="digitalState" unique="false" eType="#//DigitalValue"/>
    </eOperations>
    <eOperations name="fetchDigitalValue" unique="false" eType="#//DigitalValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="io_actuator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digitalState" unique="false"
        eType="#//DigitalValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultState" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keepOnReconnect" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eGenericSuperTypes eClassifier="#//IODevice"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFIOActorConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletIO16">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_io16"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//TinkerBrickletIO16"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//IODevice"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//InterruptListener"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFInterruptListenerConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalSensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="iosensor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pullUpResistorEnabled"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//IODevice"/>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//DigitalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFIOSensorConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletMultiTouch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_multitouch"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recalibrate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensitivity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//TinkerBrickletMultiTouch"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MultiTouchDevice"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//BrickletMultiTouchConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiTouchDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disableElectrode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickletMultiTouch"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//DigitalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//MultiTouchDeviceConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Electrode" eSuperTypes="#//MultiTouchDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="electrode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proximity" eSuperTypes="#//MultiTouchDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="proximity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletMotionDetector">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="motion_detector"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//TinkerBrickletMotionDetector"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//DigitalValue"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDualRelay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="dual_relay"/>
    <eGenericSuperTypes eClassifier="#//MInSwitchActor"/>
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MDualRelayBricklet"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletRemoteSwitch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_remote_switch"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeADevices" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeBDevices" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeCDevices" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//TinkerBrickletRemoteSwitch"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//RemoteSwitch"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//SubDeviceAdmin"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//BrickletRemoteSwitchConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSwitch" abstract="true" interface="true">
    <eGenericSuperTypes eClassifier="#//MInSwitchActor"/>
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickletRemoteSwitch"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSwitchA">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="remote_switch_a"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="houseCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiverCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeats" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eGenericSuperTypes eClassifier="#//RemoteSwitch"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//RemoteSwitchAConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSwitchB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="remote_switch_b"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeats" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eGenericSuperTypes eClassifier="#//RemoteSwitch"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//RemoteSwitchBConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSwitchC">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="remote_switch_c"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeats" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eGenericSuperTypes eClassifier="#//RemoteSwitch"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//RemoteSwitchCConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletHumidity">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="bricklet_humidity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="humiditiy" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="5"/>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//MDecimalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletHumidity"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFBaseConfiguration"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CallbackListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletDistanceIR">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_distance_ir"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="5"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletDistanceIR"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//MDecimalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFBaseConfiguration"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CallbackListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletTemperature">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_temperature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletTemperature"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//MDecimalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFBaseConfiguration"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CallbackListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletTemperatureIR">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_temperatureIR"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//TinkerBrickletTemperatureIR"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MTemperatureIRDevice"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTemperatureIRDevice">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10"/>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//MDecimalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickletTemperatureIR"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CallbackListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectTemperature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="object_temperature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emissivity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//MTemperatureIRDevice"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFObjectTemperatureConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmbientTemperature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="ambient_temperature"/>
    <eGenericSuperTypes eClassifier="#//MTemperatureIRDevice"/>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFBaseConfiguration"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletBarometer">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_barometer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="airPressure" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1000"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletBarometer"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//MDecimalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFBaseConfiguration"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MBarometerTemperature"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CallbackListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBarometerTemperature">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="barometer_temperature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//MDecimalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSubDevice">
      <eTypeArguments eClassifier="#//MBrickletBarometer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletAmbientLight">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_ambient_light"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="illuminance" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletAmbientLight"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MSensor">
      <eTypeArguments eClassifier="#//MDecimalValue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTFConfigConsumer">
      <eTypeArguments eClassifier="#//TFBaseConfiguration"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CallbackListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBrickletLCD20x4">
    <eOperations name="init" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="bricklet_LCD20x4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionPrefix" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="TFNUM&lt;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positonSuffix" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=">"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayErrors" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorPrefix" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="openhab Error:"/>
    <eGenericSuperTypes eClassifier="#//MDevice">
      <eTypeArguments eClassifier="#//MTinkerBrickletLCD20x4"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MTextActor"/>
    <eGenericSuperTypes eClassifier="#//MSubDeviceHolder">
      <eTypeArguments eClassifier="#//MLCDSubDevice"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLCD20x4Backlight" eSuperTypes="#//MInSwitchActor #//MLCDSubDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="backlight"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLCD20x4Button" eSuperTypes="#//MOutSwitchActor #//MLCDSubDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceType" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="lcd_button"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buttonNum" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callbackPeriod" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFConfig" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OHTFDevice">
    <eTypeParameters name="TFC">
      <eBounds eClassifier="#//TFConfig"/>
    </eTypeParameters>
    <eTypeParameters name="IDS">
      <eBounds eClassifier="#//Enum"/>
    </eTypeParameters>
    <eOperations name="isValidSubId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="subId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ohid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subDeviceIds" unique="false"
        upperBound="-1">
      <eGenericType eTypeParameter="#//OHTFDevice/IDS"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tfConfig" containment="true"
        resolveProxies="false">
      <eGenericType eTypeParameter="#//OHTFDevice/TFC"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ohConfig" eType="#//OHConfig"
        eOpposite="#//OHConfig/ohTfDevices"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OHTFSubDeviceAdminDevice">
    <eTypeParameters name="TFC">
      <eBounds eClassifier="#//TFConfig"/>
    </eTypeParameters>
    <eTypeParameters name="IDS">
      <eBounds eClassifier="#//Enum"/>
    </eTypeParameters>
    <eOperations name="isValidSubId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="subId" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//OHTFDevice">
      <eTypeArguments eTypeParameter="#//OHTFSubDeviceAdminDevice/TFC"/>
      <eTypeArguments eTypeParameter="#//OHTFSubDeviceAdminDevice/IDS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OHConfig">
    <eOperations name="getConfigByTFId" unique="false">
      <eGenericType eClassifier="#//OHTFDevice">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="uid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="subid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getConfigByOHId" unique="false">
      <eGenericType eClassifier="#//OHTFDevice">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="ohid" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ohTfDevices" upperBound="-1"
        containment="true" resolveProxies="false" eOpposite="#//OHTFDevice/ohConfig">
      <eGenericType eClassifier="#//OHTFDevice">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFNullConfiguration" eSuperTypes="#//TFConfig"/>
  <eClassifiers xsi:type="ecore:EClass" name="TFBaseConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callbackPeriod" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFObjectTemperatureConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emissivity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFBrickDCConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="velocity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceleration" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwmFrequency" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driveMode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="switchOnVelocity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFIOActorConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultState" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keepOnReconnect" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFInterruptListenerConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debouncePeriod" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFIOSensorConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pullUpResistorEnabled"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFServoConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="velocity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceleration" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="servoVoltage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pulseWidthMin" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pulseWidthMax" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputVoltage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrickletRemoteSwitchConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeADevices" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeBDevices" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeCDevices" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSwitchAConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="houseCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiverCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeats" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSwitchBConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeats" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteSwitchCConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeats" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiTouchDeviceConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disableElectrode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrickletMultiTouchConfiguration" eSuperTypes="#//TFConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recalibrate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensitivity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NoSubIds"/>
  <eClassifiers xsi:type="ecore:EEnum" name="IndustrialDigitalInSubIDs">
    <eLiterals name="IN0"/>
    <eLiterals name="IN1"/>
    <eLiterals name="IN2"/>
    <eLiterals name="IN3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IndustrialQuadRelayIDs">
    <eLiterals name="RELAY0"/>
    <eLiterals name="RELAY1"/>
    <eLiterals name="RELAY2"/>
    <eLiterals name="RELAY3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServoSubIDs">
    <eLiterals name="SERVO0"/>
    <eLiterals name="SERVO1"/>
    <eLiterals name="SERVO2"/>
    <eLiterals name="SERVO3"/>
    <eLiterals name="SERVO4"/>
    <eLiterals name="SERVO5"/>
    <eLiterals name="SERVO6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BarometerSubIDs">
    <eLiterals name="TEMPERATURE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IO16SubIds">
    <eLiterals name="INA0"/>
    <eLiterals name="INA1"/>
    <eLiterals name="INA2"/>
    <eLiterals name="INA3"/>
    <eLiterals name="INA4"/>
    <eLiterals name="INA5"/>
    <eLiterals name="INA6"/>
    <eLiterals name="INA7"/>
    <eLiterals name="INB0"/>
    <eLiterals name="INB1"/>
    <eLiterals name="INB2"/>
    <eLiterals name="INB3"/>
    <eLiterals name="INB4"/>
    <eLiterals name="INB5"/>
    <eLiterals name="INB6"/>
    <eLiterals name="INB7"/>
    <eLiterals name="OUTA0"/>
    <eLiterals name="OUTA1"/>
    <eLiterals name="OUTA2"/>
    <eLiterals name="OUTA3"/>
    <eLiterals name="OUTA4"/>
    <eLiterals name="OUTA5"/>
    <eLiterals name="OUTA6"/>
    <eLiterals name="OUTA7"/>
    <eLiterals name="OUTB0"/>
    <eLiterals name="OUTB1"/>
    <eLiterals name="OUTB2"/>
    <eLiterals name="OUTB3"/>
    <eLiterals name="OUTB4"/>
    <eLiterals name="OUTB5"/>
    <eLiterals name="OUTB6"/>
    <eLiterals name="OUTB7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DualRelaySubIds">
    <eLiterals name="RELAY1"/>
    <eLiterals name="RELAY2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LCDButtonSubIds">
    <eLiterals name="BUTTON0"/>
    <eLiterals name="BUTTON1"/>
    <eLiterals name="BUTTON2"/>
    <eLiterals name="BUTTON3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LCDBacklightSubIds">
    <eLiterals name="BACKLIGHT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MultiTouchSubIds">
    <eLiterals name="ELECTRODE0"/>
    <eLiterals name="ELECTRODE1"/>
    <eLiterals name="ELECTRODE2"/>
    <eLiterals name="ELECTRODE3"/>
    <eLiterals name="ELECTRODE4"/>
    <eLiterals name="ELECTRODE5"/>
    <eLiterals name="ELECTRODE6"/>
    <eLiterals name="ELECTRODE7"/>
    <eLiterals name="ELECTRODE8"/>
    <eLiterals name="ELECTRODE9"/>
    <eLiterals name="ELECTRODE10"/>
    <eLiterals name="ELECTRODE11"/>
    <eLiterals name="PROXIMITY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TemperatureIRSubIds">
    <eLiterals name="OBJECT_TEMPERATURE"/>
    <eLiterals name="AMBIENT_TEMPERATURE"/>
  </eClassifiers>
</ecore:EPackage>
